#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

struct ramfile {
    const char* name;
    const uint8_t* data;
    uint32_t size;
};

/*
 * Generated by scripts/generate_ramfs.py.
 * These symbols intentionally use BlockOS-specific names so an older
 * fs/files.cpp embedding can remain in the tree without symbol clashes.
 */
extern const struct ramfile __blockos_ramfs_start[];
extern const struct ramfile __blockos_ramfs_end[];

const uint8_t* ramfs_get(const char* name, uint32_t* size_out);

#ifdef __cplusplus
}
#endif
