#!/bin/sh
set -eu
ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
export GNOME_BUILD_ROOT="${GNOME_BUILD_ROOT:-$ROOT}"
export GNOME_SOURCES="${GNOME_SOURCES:-$ROOT/sources}"
export GNOME_BUILDS="${GNOME_BUILDS:-$ROOT/builds}"
export GNOME_OUT="${GNOME_OUT:-$ROOT/out/rootfs}"
export BLOCKOS_SYSROOT="${BLOCKOS_SYSROOT:-$ROOT/sysroot}"
export BLOCKOS_TRIPLET="${BLOCKOS_TRIPLET:-x86_64-blockos}"
export BLOCKOS_TOOLCHAIN="${BLOCKOS_TOOLCHAIN:-x86_64-blockos-}"
export BLOCKOS_CC="${BLOCKOS_CC:-${BLOCKOS_TOOLCHAIN}gcc}"
export BLOCKOS_CXX="${BLOCKOS_CXX:-${BLOCKOS_TOOLCHAIN}g++}"
export BLOCKOS_AR="${BLOCKOS_AR:-${BLOCKOS_TOOLCHAIN}ar}"
export BLOCKOS_RANLIB="${BLOCKOS_RANLIB:-${BLOCKOS_TOOLCHAIN}ranlib}"
export BLOCKOS_STRIP="${BLOCKOS_STRIP:-${BLOCKOS_TOOLCHAIN}strip}"
export PKG_CONFIG_SYSROOT_DIR="$BLOCKOS_SYSROOT"
export PKG_CONFIG_LIBDIR="$BLOCKOS_SYSROOT/System/lib/pkgconfig:$BLOCKOS_SYSROOT/System/share/pkgconfig:$BLOCKOS_SYSROOT/usr/lib/pkgconfig"
export PKG_CONFIG_PATH=""
export PATH="$GNOME_BUILD_ROOT/tools/bin:$PATH"
export CFLAGS="${CFLAGS:--O2 -fPIC -fno-exceptions -fno-rtti}"
export CXXFLAGS="${CXXFLAGS:--O2 -fPIC -fno-exceptions -fno-rtti}"
export LDFLAGS="${LDFLAGS:--L/system/lib -Wl,-rpath,/system/lib -Wl,--dynamic-linker=/system/lib/ld.so}"
export MESON_CROSS_FILE="$GNOME_BUILD_ROOT/ports/gnome42/cross.ini"
export DESTDIR="$GNOME_OUT"
mkdir -p "$GNOME_SOURCES" "$GNOME_BUILDS" "$GNOME_OUT/System/bin" "$GNOME_OUT/System/lib" "$GNOME_OUT/System/share" "$GNOME_OUT/System/etc"
