#!/usr/bin/env python3
"""Generate the embedded BlockOS RAMFS assembly.

Symlinks are preserved as RAMFS entries that point at their resolved target
payload. This is important for multi-call binaries such as Toybox: hundreds
of applet symlinks must NOT embed the same binary hundreds of times.
"""
from __future__ import annotations

import posixpath
import sys
from pathlib import Path

REQUIRED = ("bin/sh", "bin/toybox")


def asm_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def collect(root: Path):
    root = root.resolve()
    files = []
    for path in sorted(root.rglob("*")):
        if path.is_symlink():
            try:
                data_path = path.resolve(strict=True)
            except FileNotFoundError:
                print(f"[RAMFS][ERROR] broken symlink: {path}", file=sys.stderr)
                raise SystemExit(1)
            if not data_path.is_file():
                print(f"[RAMFS][ERROR] symlink target is not a file: {path} -> {data_path}", file=sys.stderr)
                raise SystemExit(1)
        elif path.is_file():
            data_path = path
        else:
            continue

        try:
            data_path.relative_to(root)
        except ValueError:
            print(f"[RAMFS][ERROR] file points outside rootfs: {path} -> {data_path}", file=sys.stderr)
            raise SystemExit(1)

        rel = path.relative_to(root).as_posix()
        if not rel or rel.startswith("../"):
            continue
        rel = "/" + posixpath.normpath(rel).lstrip("/")
        files.append((rel, data_path.resolve()))
    return files


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else "rootfs").resolve()
    output = Path(sys.argv[2] if len(sys.argv) > 2 else "fs/ramfs_generated.S").resolve()

    if not root.is_dir():
        print(f"[RAMFS][ERROR] rootfs directory not found: {root}", file=sys.stderr)
        return 1

    entries = collect(root)
    if not entries:
        print(f"[RAMFS][ERROR] rootfs is empty: {root}", file=sys.stderr)
        return 1

    names = {name for name, _ in entries}
    missing = [p for p in REQUIRED if "/" + p not in names]
    if missing:
        print("[RAMFS][ERROR] required rootfs files are missing:", file=sys.stderr)
        for item in missing:
            print(f"  /{item}", file=sys.stderr)
        return 1

    # One payload per resolved target. Toybox symlinks therefore share one
    # embedded data block instead of duplicating the binary for every applet.
    unique_data = []
    data_index = {}
    for _, data_path in entries:
        if data_path not in data_index:
            data_index[data_path] = len(unique_data)
            unique_data.append(data_path)

    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Auto-generated by scripts/generate_ramfs.py. */",
        '.section .ramfs,"a",@progbits',
        ".p2align 3",
        ".globl __blockos_ramfs_start",
        ".globl __blockos_ramfs_end",
        ".type __blockos_ramfs_start,@object",
        "__blockos_ramfs_start:",
    ]

    for index, (name, data_path) in enumerate(entries):
        di = data_index[data_path]
        lines += [
            f"    .quad __blockos_ramfs_name_{index}",
            f"    .quad __blockos_ramfs_data_{di}",
            f"    .long __blockos_ramfs_size_{di}",
            "    .long 0",
        ]

    lines += ["__blockos_ramfs_end:", "", ".p2align 1"]

    for di, data_path in enumerate(unique_data):
        lines += [
            f"__blockos_ramfs_data_{di}:",
            f"    .incbin {asm_string(str(data_path))}",
            f"__blockos_ramfs_data_{di}_end:",
            f"__blockos_ramfs_size_{di} = __blockos_ramfs_data_{di}_end - __blockos_ramfs_data_{di}",
            "",
        ]

    for index, (name, _) in enumerate(entries):
        lines += [
            f"__blockos_ramfs_name_{index}:",
            f"    .asciz {asm_string(name)}",
            "",
        ]

    output.write_text("\\n".join(lines) + "\\n", encoding="utf-8")

    total_bytes = sum(path.stat().st_size for _, path in entries)
    unique_bytes = sum(path.stat().st_size for path in unique_data)
    print(f"[RAMFS] files:        {len(entries)}")
    print(f"[RAMFS] unique data:   {len(unique_data)}")
    print(f"[RAMFS] logical bytes: {total_bytes}")
    print(f"[RAMFS] stored bytes:  {unique_bytes}")
    print(f"[RAMFS] rootfs:        {root}")
    print(f"[RAMFS] asm:           {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
