#!/usr/bin/env python3
"""Generate a single .ramfs ELF section containing the complete BlockOS rootfs.

Usage:
    python3 scripts/generate_ramfs.py [ROOTFS] [OUTPUT]

Defaults:
    ROOTFS = rootfs
    OUTPUT = fs/ramfs_generated.S

The generated assembly contains one table followed by all path strings and
file bytes. Everything stays in .ramfs so an EFI objcopy rule that keeps
'-j .ramfs' keeps the complete embedded root filesystem too.
"""

from __future__ import annotations

import posixpath
import sys
from pathlib import Path

REQUIRED = (
    "bin/sh",
    "bin/busybox",
)


def asm_string(value: str) -> str:
    escaped = value.replace('\\', '\\\\').replace('"', '\\"')
    return f'"{escaped}"'


def collect(root: Path) -> list[tuple[str, Path]]:
    files: list[tuple[str, Path]] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(root).as_posix()
        if not rel or rel.startswith("../"):
            continue
        rel = "/" + posixpath.normpath(rel).lstrip("/")
        files.append((rel, path))
    return files


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else "rootfs").resolve()
    output = Path(sys.argv[2] if len(sys.argv) > 2 else "fs/ramfs_generated.S").resolve()

    if not root.is_dir():
        print(f"[RAMFS][ERROR] rootfs directory not found: {root}", file=sys.stderr)
        return 1

    entries = collect(root)
    if not entries:
        print(f"[RAMFS][ERROR] rootfs is empty: {root}", file=sys.stderr)
        return 1

    names = {name for name, _ in entries}
    missing = [path for path in REQUIRED if "/" + path not in names]
    if missing:
        print("[RAMFS][ERROR] required rootfs files are missing:", file=sys.stderr)
        for item in missing:
            print(f"  /{item}", file=sys.stderr)
        return 1

    output.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines += [
        "/* Auto-generated by scripts/generate_ramfs.py. */",
        ".section .ramfs,\"a\",@progbits",
        ".p2align 3",
        ".globl __blockos_ramfs_start",
        ".globl __blockos_ramfs_end",
        ".type __blockos_ramfs_start,@object",
        "__blockos_ramfs_start:",
    ]

    for index, (name, _) in enumerate(entries):
        lines += [
            f"    .quad __blockos_ramfs_name_{index}",
            f"    .quad __blockos_ramfs_data_{index}",
            f"    .long __blockos_ramfs_size_{index}",
            "    .long 0",
        ]

    lines += [
        "__blockos_ramfs_end:",
        "",
        ".p2align 1",
    ]

    for index, (name, path) in enumerate(entries):
        # Use absolute build-time paths to make assembly independent of the
        # caller's current working directory.
        lines += [
            f"__blockos_ramfs_name_{index}:",
            f"    .asciz {asm_string(name)}",
            f"    .p2align 3",
            f"__blockos_ramfs_data_{index}:",
            f"    .incbin {asm_string(str(path))}",
            f"__blockos_ramfs_data_{index}_end:",
            f"__blockos_ramfs_size_{index} = __blockos_ramfs_data_{index}_end - __blockos_ramfs_data_{index}",
            "",
        ]

    output.write_text("\n".join(lines) + "\n", encoding="utf-8")

    total_bytes = sum(path.stat().st_size for _, path in entries)
    print(f"[RAMFS] files: {len(entries)}")
    print(f"[RAMFS] bytes: {total_bytes}")
    print(f"[RAMFS] rootfs: {root}")
    print(f"[RAMFS] asm:    {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
