#!/usr/bin/env python3
# scripts/menuconfig.py - BlockOS Linuxosabb ncurses konfigurátor
# Teljesen billentyűzetes, scrollozható, kategóriás, .config-független.
# Mentés: blockos.settings + kernel/blockos_config.h

import curses
from curses import textpad
import os
import textwrap


OPTIONS = [
    ("Kernel", "CONFIG_SYSTEMD", True,  "systemd-szeru init", "Aktivalja a BlockOS init/fuggosegi kezelo reteget."),
    ("Kernel", "CONFIG_DEBUG_PANIC", True, "Debug panic kepernyo", "Sulyos hiba eseten regiszter-dumpot mutat."),
    ("Kernel", "CONFIG_PREEMPT", True, "Preemptive scheduler", "A kernel idoszeletesebb feladatkezeleset engedelyezi."),
    ("Kernel", "CONFIG_SMP", False, "SMP tamogatas", "Tobbszalas, tobb CPU / mag kezelese."),
    ("Drivers", "CONFIG_VIRTIO_NET", True, "VirtIO halozat", "VirtIO alapu haloati driver."),
    ("Drivers", "CONFIG_VIRTIO_BLOCK", True, "VirtIO block", "VirtIO alapu lemez driver."),
    ("Drivers", "CONFIG_VIRTIO_GPU", False, "VirtIO GPU", "Gyorsabb grafikus kimenet VirtIO GPU-val."),
    ("Drivers", "CONFIG_PS2_KEYBOARD", True, "PS/2 billentyuzet", "Alap billentyuzet driver."),
    ("Drivers", "CONFIG_PS2_MOUSE", True, "PS/2 egér", "Alap eger driver."),
    ("Filesystem", "CONFIG_VFS", True, "VFS reteg", "Virtualis fajlrendszer reteg."),
    ("Filesystem", "CONFIG_EXT4", True, "EXT4 tamogatas", "EXT4 olvasas/iras az uj struktura szerint."),
    ("Filesystem", "CONFIG_RAMFS", True, "RAMFS", "Memoriaban elo fajlrendszer."),
    ("Apps", "CONFIG_APP_BROWSER", True, "Browser ELF", "Grafikus webbongeszo betoltese."),
    ("Apps", "CONFIG_APP_SNAKE", False, "Snake ELF", "Grafikus kigyos jatek betoltese."),
    ("Graphics", "CONFIG_FB", True, "Framebuffer", "Framebuffer grafikus kimenet."),
    ("Graphics", "CONFIG_DOUBLE_BUFFER", True, "Double buffering", "Villodasmentes rajzolas dupla pufferrel."),
]

CATEGORIES = ["All", "Kernel", "Drivers", "Filesystem", "Apps", "Graphics"]


def save_config():
    os.makedirs("kernel", exist_ok=True)

    with open("blockos.settings", "w", encoding="utf-8") as f:
        for cat, macro, enabled, label, _ in OPTIONS:
            f.write(f"{macro}={'ON' if enabled else 'OFF'}\n")

    with open("kernel/blockos_config.h", "w", encoding="utf-8") as f:
        f.write("// AUTOGENERATED BY BLOCKOS MENUCONFIG - DO NOT EDIT\n")
        f.write("#ifndef BLOCKOS_CONFIG_H\n#define BLOCKOS_CONFIG_H\n\n")
        for _, macro, enabled, _, _ in OPTIONS:
            if enabled:
                f.write(f"#define {macro} 1\n")
            else:
                f.write(f"// #define {macro} 0\n")
        f.write("\n#endif\n")


def wrap_text(text, width):
    lines = []
    for para in text.splitlines():
        if not para.strip():
            lines.append("")
        else:
            lines.extend(textwrap.wrap(para, width=width) or [""])
    return lines


def safe_addstr(stdscr, y, x, text, attr=0):
    h, w = stdscr.getmaxyx()
    if y < 0 or y >= h or x >= w:
        return
    if x < 0:
        text = text[-x:]
        x = 0
    if x >= w:
        return
    try:
        stdscr.addstr(y, x, text[: max(0, w - x - 1)], attr)
    except curses.error:
        pass


def build_index_list(category, search_query):
    idxs = []
    sq = search_query.lower().strip()
    for i, opt in enumerate(OPTIONS):
        if category != "All" and opt[0] != category:
            continue
        if sq:
            hay = " ".join([opt[0], opt[1], opt[3], opt[4]]).lower()
            if sq not in hay:
                continue
        idxs.append(i)
    return idxs


def load_last_state():
    if not os.path.exists("blockos.settings"):
        return
    values = {}
    with open("blockos.settings", "r", encoding="utf-8", errors="ignore") as f:
        for raw in f:
            line = raw.strip()
            if not line or "=" not in line:
                continue
            k, v = line.split("=", 1)
            values[k.strip()] = v.strip().upper()
    for i, opt in enumerate(OPTIONS):
        macro = opt[1]
        if macro in values:
            OPTIONS[i] = (opt[0], opt[1], values[macro] in ("ON", "Y", "1", "TRUE"), opt[3], opt[4])


def draw_header(stdscr):
    h, w = stdscr.getmaxyx()
    safe_addstr(stdscr, 1, 2, " blockos Kernel Configuration - BlockOS Setup Utility ", curses.color_pair(3) | curses.A_BOLD)
    safe_addstr(
        stdscr, 2, 2,
        "F1/? Help | / Search | Tab/Left/Right Category | Up/Down Move | PgUp/PgDn Scroll | Space Toggle | F10/Enter Save | F9/q/Esc Quit",
        curses.color_pair(1)
    )
    safe_addstr(stdscr, 4, 2, "Categories: ", curses.color_pair(1))
    x = 14
    for i, cat in enumerate(CATEGORIES):
        label = f" < {cat} > " if i == 0 else f"   {cat}   "
        # only visual on selected category is handled elsewhere
        safe_addstr(stdscr, 4, x, label, curses.color_pair(1))
        x += len(label) + 1


def draw_menu(stdscr):
    curses.start_color()
    curses.use_default_colors()

    curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLUE)   # base
    curses.init_pair(2, curses.COLOR_BLACK, curses.COLOR_WHITE)  # selected
    curses.init_pair(3, curses.COLOR_YELLOW, curses.COLOR_BLUE)  # title
    curses.init_pair(4, curses.COLOR_CYAN, curses.COLOR_BLUE)    # borders/info
    curses.init_pair(5, curses.COLOR_RED, curses.COLOR_WHITE)     # warnings

    curses.curs_set(0)
    stdscr.keypad(True)

    load_last_state()

    cat_idx = 0
    selection = 0
    scroll = 0
    search_query = ""
    status = "Ready."

    while True:
        stdscr.bkgd(" ", curses.color_pair(1))
        stdscr.erase()
        h, w = stdscr.getmaxyx()

        if h < 18 or w < 78:
            safe_addstr(stdscr, 1, 2, "Terminal too small. Resize to at least 78x18.", curses.color_pair(5) | curses.A_BOLD)
            safe_addstr(stdscr, 3, 2, "Press any key...", curses.color_pair(2))
            stdscr.refresh()
            stdscr.getch()
            continue

        draw_header(stdscr)

        # Selected category bar
        safe_addstr(stdscr, 4, 14, "", curses.color_pair(1))
        x = 14
        for i, cat in enumerate(CATEGORIES):
            label = f" < {cat} > " if i == cat_idx else f"   {cat}   "
            attr = curses.color_pair(2) if i == cat_idx else curses.color_pair(1)
            safe_addstr(stdscr, 4, x, label, attr)
            x += len(label) + 1

        active_category = CATEGORIES[cat_idx]
        visible_indices = build_index_list(active_category, search_query)

        if selection >= len(visible_indices):
            selection = max(0, len(visible_indices) - 1)
        if selection < 0:
            selection = 0

        box_y, box_x = 6, 2
        box_h = max(6, h - 13)
        box_w = w - 6

        textpad.rectangle(stdscr, box_y, box_x, box_y + box_h, box_x + box_w)

        list_height = max(1, box_h - 1)
        if selection < scroll:
            scroll = selection
        elif selection >= scroll + list_height:
            scroll = selection - list_height + 1

        if not visible_indices:
            safe_addstr(stdscr, box_y + 2, box_x + 3, "No options match the current filter.", curses.color_pair(1))
        else:
            end = min(len(visible_indices), scroll + list_height)
            for row, opt_idx in enumerate(visible_indices[scroll:end], start=0):
                opt = OPTIONS[opt_idx]
                y = box_y + 1 + row
                marker = "[*]" if opt[2] else "[ ]"
                line = f"{marker} {opt[3]}"

                if scroll + row == selection:
                    safe_addstr(stdscr, y, box_x + 1, " " * (box_w - 1), curses.color_pair(2))
                    safe_addstr(stdscr, y, box_x + 2, line, curses.color_pair(2))
                else:
                    safe_addstr(stdscr, y, box_x + 2, line, curses.color_pair(1))

            current = OPTIONS[visible_indices[selection]]
            info_y = box_y + box_h + 1

            safe_addstr(stdscr, info_y, 2, f"Search: '{search_query}'" if search_query else "Search: (none)", curses.color_pair(3))
            safe_addstr(stdscr, info_y + 1, 2, f"Selected: {current[1]} | Category: {current[0]}", curses.color_pair(3))

            desc = wrap_text(current[4], max(20, w - 8))
            for i, line in enumerate(desc[:2]):
                safe_addstr(stdscr, info_y + 2 + i, 2, line, curses.color_pair(1))

        safe_addstr(stdscr, h - 2, 2, f"Status: {status}", curses.color_pair(4))
        stdscr.refresh()

        key = stdscr.getch()

        if key in (curses.KEY_UP, ord("w"), ord("k")):
            if visible_indices:
                selection = (selection - 1) % len(visible_indices)
        elif key in (curses.KEY_DOWN, ord("s"), ord("j")):
            if visible_indices:
                selection = (selection + 1) % len(visible_indices)
        elif key == curses.KEY_PPAGE:
            if visible_indices:
                selection = max(0, selection - 5)
        elif key == curses.KEY_NPAGE:
            if visible_indices:
                selection = min(len(visible_indices) - 1, selection + 5)
        elif key == curses.KEY_HOME:
            selection = 0
        elif key == curses.KEY_END:
            if visible_indices:
                selection = len(visible_indices) - 1
        elif key in (curses.KEY_LEFT, curses.KEY_RIGHT, 9):  # Left/Right/Tab
            if key == curses.KEY_LEFT:
                cat_idx = (cat_idx - 1) % len(CATEGORIES)
            else:
                cat_idx = (cat_idx + 1) % len(CATEGORIES)
            selection = 0
            scroll = 0
            status = f"Category: {CATEGORIES[cat_idx]}"
        elif key == ord(" "):
            if visible_indices:
                opt_idx = visible_indices[selection]
                cat, macro, enabled, label, desc = OPTIONS[opt_idx]
                OPTIONS[opt_idx] = (cat, macro, not enabled, label, desc)
                status = f"{macro} -> {'ON' if not enabled else 'OFF'}"
        elif key in (curses.KEY_F1, ord("?")):
            if visible_indices:
                opt = OPTIONS[visible_indices[selection]]
                stdscr.clear()
                h2, w2 = stdscr.getmaxyx()
                textpad.rectangle(stdscr, 2, 4, h2 - 3, w2 - 5)
                safe_addstr(stdscr, 3, 6, f"Help: {opt[3]}", curses.color_pair(3) | curses.A_BOLD)
                safe_addstr(stdscr, 5, 6, f"Macro: {opt[1]}", curses.color_pair(1))
                safe_addstr(stdscr, 6, 6, f"Category: {opt[0]}", curses.color_pair(1))
                help_lines = wrap_text(opt[4], max(20, w2 - 12))
                for i, line in enumerate(help_lines):
                    if 8 + i >= h2 - 5:
                        break
                    safe_addstr(stdscr, 8 + i, 6, line, curses.color_pair(1))
                safe_addstr(stdscr, h2 - 5, 6, "Press any key to return...", curses.color_pair(2))
                stdscr.refresh()
                stdscr.getch()
                status = "Help closed."
        elif key == ord("/"):
            prompt = "Search: "
            safe_addstr(stdscr, h - 4, 2, " " * (w - 4), curses.color_pair(1))
            safe_addstr(stdscr, h - 4, 2, prompt, curses.color_pair(3))
            curses.curs_set(1)
            curses.echo()
            try:
                raw = stdscr.getstr(h - 4, 2 + len(prompt), 40)
                search_query = raw.decode("utf-8", errors="ignore").strip().lower()
            except Exception:
                search_query = ""
            curses.noecho()
            curses.curs_set(0)
            selection = 0
            scroll = 0
            status = "Search updated." if search_query else "Search cleared."
        elif key in (curses.KEY_F10, 10, 13):
            save_config()
            return True
        elif key in (curses.KEY_F9, 27, ord("q")):
            # Esc first clears search; second press quits
            if search_query:
                search_query = ""
                selection = 0
                scroll = 0
                status = "Search cleared."
            else:
                return False


def main():
    try:
        saved = curses.wrapper(draw_menu)
    except KeyboardInterrupt:
        saved = False

    if saved:
        print("\n[SUCCESS] Configuration saved.")
        print("  - blockos.settings updated")
        print("  - kernel/blockos_config.h updated\n")
    else:
        print("\n[CANCEL] Exited without saving.\n")


if __name__ == "__main__":
    main()
