#pragma once

#include <cstdint>

namespace blockos::syscall {
std::int64_t sys_read();
std::int64_t sys_write();
std::int64_t sys_openat();
std::int64_t sys_close();
std::int64_t sys_fstat();
std::int64_t sys_mmap();
std::int64_t sys_munmap();
std::int64_t sys_mprotect();
std::int64_t sys_brk();
std::int64_t sys_setuid();
std::int64_t sys_setgid();
std::int64_t sys_seteuid();
std::int64_t sys_setegid();
std::int64_t sys_getuid();
std::int64_t sys_getgid();
std::int64_t sys_geteuid();
std::int64_t sys_getegid();
std::int64_t sys_setgroups();
std::int64_t sys_getgroups();
std::int64_t sys_chdir();
std::int64_t sys_getcwd();
std::int64_t sys_access();
std::int64_t sys_readlink();
std::int64_t sys_stat();
std::int64_t sys_lstat();
std::int64_t sys_socket();
std::int64_t sys_bind();
std::int64_t sys_listen();
std::int64_t sys_accept();
std::int64_t sys_accept4();
std::int64_t sys_connect();
std::int64_t sys_sendto();
std::int64_t sys_recvfrom();
std::int64_t sys_shutdown();
std::int64_t sys_setsockopt();
std::int64_t sys_getsockopt();
std::int64_t sys_epoll_create1();
std::int64_t sys_epoll_ctl();
std::int64_t sys_epoll_wait();
std::int64_t sys_poll();
std::int64_t sys_ppoll();
std::int64_t sys_futex();
std::int64_t sys_clone();
std::int64_t sys_wait4();
std::int64_t sys_exit();
std::int64_t sys_exit_group();
std::int64_t sys_sched_yield();
std::int64_t sys_nanosleep();
std::int64_t sys_execve();
std::int64_t sys_prctl();
std::int64_t sys_getrandom();
std::int64_t sys_clock_gettime();
std::int64_t sys_getpid();
std::int64_t sys_getppid();
std::int64_t sys_gettid();
std::int64_t sys_set_tid_address();
std::int64_t sys_capget();
std::int64_t sys_capset();
std::int64_t sys_ioctl();
std::int64_t sys_readv();
std::int64_t sys_writev();
}
