#pragma once

#include <cstdint>

namespace blockos::syscall {

enum Number : std::uint64_t {
    SYS_read = 0,
    SYS_write = 1,
    SYS_openat = 2,
    SYS_close = 3,
    SYS_fstat = 4,
    SYS_mmap = 5,
    SYS_munmap = 6,
    SYS_mprotect = 7,
    SYS_brk = 8,
    SYS_setuid = 9,
    SYS_setgid = 10,
    SYS_seteuid = 11,
    SYS_setegid = 12,
    SYS_getuid = 13,
    SYS_getgid = 14,
    SYS_geteuid = 15,
    SYS_getegid = 16,
    SYS_setgroups = 17,
    SYS_getgroups = 18,
    SYS_chdir = 19,
    SYS_getcwd = 20,
    SYS_access = 21,
    SYS_readlink = 22,
    SYS_stat = 23,
    SYS_lstat = 24,
    SYS_socket = 25,
    SYS_bind = 26,
    SYS_listen = 27,
    SYS_accept = 28,
    SYS_accept4 = 29,
    SYS_connect = 30,
    SYS_sendto = 31,
    SYS_recvfrom = 32,
    SYS_shutdown = 33,
    SYS_setsockopt = 34,
    SYS_getsockopt = 35,
    SYS_epoll_create1 = 36,
    SYS_epoll_ctl = 37,
    SYS_epoll_wait = 38,
    SYS_poll = 39,
    SYS_ppoll = 40,
    SYS_futex = 41,
    SYS_clone = 42,
    SYS_wait4 = 43,
    SYS_exit = 44,
    SYS_exit_group = 45,
    SYS_sched_yield = 46,
    SYS_nanosleep = 47,
    SYS_execve = 48,
    SYS_prctl = 49,
    SYS_getrandom = 50,
    SYS_clock_gettime = 51,
    SYS_getpid = 52,
    SYS_getppid = 53,
    SYS_gettid = 54,
    SYS_set_tid_address = 55,
    SYS_capget = 56,
    SYS_capset = 57,
    SYS_ioctl = 58,
    SYS_readv = 59,
    SYS_writev = 60,
    SYS_unknown = 0xFFFFFFFFFFFFFFFFULL
};

}
